//
// © 2023 Manicek
//

import SwiftUI

extension LocalizedStringKey {
    // MARK: - Special
    static let empty: LocalizedStringKey = "-"
    
    // MARK: - MainView titles
    static let mainViewTitlePlayers: LocalizedStringKey = "players"
    static let mainViewTitlePlaces: LocalizedStringKey = "places"
    static let mainViewTitleCombat: LocalizedStringKey = "combat"
    static let mainViewTitleTables: LocalizedStringKey = "tables"
    static let mainViewTitleRolling: LocalizedStringKey = "rolling"
    static let mainViewTitleTalents: LocalizedStringKey = "talents"
    static let mainViewTitleEncounters: LocalizedStringKey = "encounters"
    static let mainViewTitleNPCs: LocalizedStringKey = "npcs"
    
    // MARK: - Money
    static let coinCopper: LocalizedStringKey = "copperCoin"
    static let coinCopperSome: LocalizedStringKey = "copperCoinsSome"
    static let coinCopperMany: LocalizedStringKey = "copperCoinsMany"
    static let coinSilver: LocalizedStringKey = "silverCoin"
    static let coinSilverSome: LocalizedStringKey = "silverCoinsSome"
    static let coinSilverMany: LocalizedStringKey = "silverCoinsMany"
    static let coinGold: LocalizedStringKey = "goldCoin"
    static let coinGoldSome: LocalizedStringKey = "goldCoinsSome"
    static let coinGoldMany: LocalizedStringKey = "goldCoinsMany"
    
    // MARK: - Character
    static let characterPride: LocalizedStringKey = "pride"
    static let characterDarkSecret: LocalizedStringKey = "darkSecret"
    static let characterReputation: LocalizedStringKey = "reputation"
    static let characterAge: LocalizedStringKey = "age"
    static let characterGenderMale: LocalizedStringKey = "genderMale"
    static let characterGenderFemale: LocalizedStringKey = "genderFemale"
    static let characterGenderOther: LocalizedStringKey = "genderOther"
    static let characterLevel: LocalizedStringKey = "level"
    static let characterRank: LocalizedStringKey = "rank"
    static let characterWillpower: LocalizedStringKey = "willpower"
    
    // MARK: - Attributes
    static let attributes: LocalizedStringKey = "attributes"
    static let attributesStrength: LocalizedStringKey = "strength"
    static let attributesAgility: LocalizedStringKey = "agility"
    static let attributesWits: LocalizedStringKey = "wits"
    static let attributesEmpathy: LocalizedStringKey = "empathy"
    
    // MARK: - Skills
    static let skills: LocalizedStringKey = "skills"
    static let skillsMight: LocalizedStringKey = "might"
    static let skillsEndurance: LocalizedStringKey = "endurance"
    static let skillsMelee: LocalizedStringKey = "melee"
    static let skillsCrafting: LocalizedStringKey = "crafting"
    static let skillsStealth: LocalizedStringKey = "stealth"
    static let skillsSleightOfHand: LocalizedStringKey = "sleightOfHand"
    static let skillsMove: LocalizedStringKey = "move"
    static let skillsMarksmanship: LocalizedStringKey = "marksmanship"
    static let skillsScouting: LocalizedStringKey = "scouting"
    static let skillsLore: LocalizedStringKey = "lore"
    static let skillsSurvival: LocalizedStringKey = "survival"
    static let skillsInsight: LocalizedStringKey = "insight"
    static let skillsManipulation: LocalizedStringKey = "manipulation"
    static let skillsPerformance: LocalizedStringKey = "performance"
    static let skillsHealing: LocalizedStringKey = "healing"
    static let skillsAnimalHandling: LocalizedStringKey = "animalHandling"
    
    // MARK: - Talents
    static let talents: LocalizedStringKey = "talents"
    static let talentAdaptive: LocalizedStringKey = "adaptive"
    static let talentInnerPeace: LocalizedStringKey = "innerPeace"
    static let talentPsychicPower: LocalizedStringKey = "psychicPower"
    static let talentTrueGrit: LocalizedStringKey = "trueGrit"
    static let talentHardToCatch: LocalizedStringKey = "hardToCatch"
    static let talentHuntingInstincts: LocalizedStringKey = "huntingInstincts"
    static let talentUnbreakable: LocalizedStringKey = "unbreakable"
    static let talentNocturnal: LocalizedStringKey = "nocturnal"
    static let talentPathOfHealing: LocalizedStringKey = "pathOfHealing"
    static let talentPathOfShiftingShapes: LocalizedStringKey = "pathOfShiftingShapes"
    static let talentPathOfSight: LocalizedStringKey = "pathOfSight"
    static let talentPathOfTheBlade: LocalizedStringKey = "pathOfTheBlade"
    static let talentPathOfTheEnemy: LocalizedStringKey = "pathOfTheEnemy"
    static let talentPathOfTheShield: LocalizedStringKey = "pathOfTheShield"
    static let talentPathOfTheArrow: LocalizedStringKey = "pathOfTheArrow"
    static let talentPathOfTheBeast: LocalizedStringKey = "pathOfTheBeast"
    static let talentPathOfTheForest: LocalizedStringKey = "pathOfTheForest"
    static let talentPathOfTheHymn: LocalizedStringKey = "pathOfTheHymn"
    static let talentPathOfTheSong: LocalizedStringKey = "pathOfTheSong"
    static let talentPathOfTheWarcry: LocalizedStringKey = "pathOfTheWarcry"
    static let talentPathOfTreasures: LocalizedStringKey = "pathOfTreasures"
    static let talentPathOfWords: LocalizedStringKey = "pathOfWords"
    static let talentPathOfManyThings: LocalizedStringKey = "pathOfManyThings"
    static let talentPathOfTheCompanion: LocalizedStringKey = "pathOfTheCompanion"
    static let talentPathOfTheKnight: LocalizedStringKey = "pathOfTheKnight"
    static let talentPathOfThePlains: LocalizedStringKey = "pathOfThePlains"
    static let talentPathOfTheFace: LocalizedStringKey = "pathOfTheFace"
    static let talentPathOfTheKiller: LocalizedStringKey = "pathOfTheKiller"
    static let talentPathOfPoison: LocalizedStringKey = "pathOfPoison"
    static let talentPathOfBlood: LocalizedStringKey = "pathOfBlood"
    static let talentPathOfDeath: LocalizedStringKey = "pathOfDeath"
    static let talentPathOfSigns: LocalizedStringKey = "pathOfSigns"
    static let talentPathOfStone: LocalizedStringKey = "pathOfStone"
    static let talentAmbidextrous: LocalizedStringKey = "ambidextrous"
    static let talentAxeFighter: LocalizedStringKey = "axeFighter"
    static let talentBerserker: LocalizedStringKey = "berserker"
    static let talentBowyer: LocalizedStringKey = "bowyer"
    static let talentBrawler: LocalizedStringKey = "brawler"
    static let talentBuilder: LocalizedStringKey = "builder"
    static let talentChef: LocalizedStringKey = "chef"
    static let talentColdBlooded: LocalizedStringKey = "coldBlooded"
    static let talentDefender: LocalizedStringKey = "defender"
    static let talentDragonslayer: LocalizedStringKey = "dragonslayer"
    static let talentExecutioner: LocalizedStringKey = "executioner"
    static let talentFastFootwork: LocalizedStringKey = "fastFootwork"
    static let talentFastShooter: LocalizedStringKey = "fastShooter"
    static let talentFearless: LocalizedStringKey = "fearless"
    static let talentFirmGrip: LocalizedStringKey = "firmGrip"
    static let talentFisher: LocalizedStringKey = "fisher"
    static let talentHammerFighter: LocalizedStringKey = "hammerFighter"
    static let talentHerbalist: LocalizedStringKey = "herbalist"
    static let talentHorsebackFighter: LocalizedStringKey = "horsebackFighter"
    static let talentIncorruptible: LocalizedStringKey = "incorruptible"
    static let talentKnifeFighter: LocalizedStringKey = "knifeFighter"
    static let talentLightningFast: LocalizedStringKey = "lightningFast"
    static let talentLockpicker: LocalizedStringKey = "lockpicker"
    static let talentLucky: LocalizedStringKey = "lucky"
    static let talentMasterOfTheHunt: LocalizedStringKey = "masterOfTheHunt"
    static let talentMeleeCharge: LocalizedStringKey = "meleeCharge"
    static let talentPackRat: LocalizedStringKey = "packRat"
    static let talentPainResistant: LocalizedStringKey = "painResistant"
    static let talentPathfinder: LocalizedStringKey = "pathfinder"
    static let talentPoisoner: LocalizedStringKey = "poisoner"
    static let talentQuartermaster: LocalizedStringKey = "quartermaster"
    static let talentQuickdraw: LocalizedStringKey = "quickdraw"
    static let talentSailor: LocalizedStringKey = "sailor"
    static let talentSharpshooter: LocalizedStringKey = "sharpshooter"
    static let talentSharpTongue: LocalizedStringKey = "sharpTongue"
    static let talentShieldFighter: LocalizedStringKey = "shieldFighter"
    static let talentSixthSense: LocalizedStringKey = "sixthSense"
    static let talentSmith: LocalizedStringKey = "smith"
    static let talentSpearFighter: LocalizedStringKey = "spearFighter"
    static let talentSteadyFeet: LocalizedStringKey = "steadyFeet"
    static let talentSwordFighter: LocalizedStringKey = "swordFighter"
    static let talentTailor: LocalizedStringKey = "tailor"
    static let talentTanner: LocalizedStringKey = "tanner"
    static let talentThreatening: LocalizedStringKey = "threatening"
    static let talentThrowingArm: LocalizedStringKey = "throwingArm"
    static let talentWanderer: LocalizedStringKey = "wanderer"
    
    // MARK: - States
    static let states: LocalizedStringKey = "states"
    static let stateSleepy: LocalizedStringKey = "sleepy"
    static let stateThirsty: LocalizedStringKey = "thirsty"
    static let stateHungry: LocalizedStringKey = "hungry"
    static let stateCold: LocalizedStringKey = "cold"
    
    // MARK: - Consumables
    static let consumables: LocalizedStringKey = "consumables"
    static let consumableFood: LocalizedStringKey = "food"
    static let consumableWater: LocalizedStringKey = "water"
    static let consumableArrows: LocalizedStringKey = "arrows"
    static let consumableTorches: LocalizedStringKey = "torches"
    
    // MARK: - Items
    static let itemsMeleeWeapon: LocalizedStringKey = "meleeWeapon"
    static let itemsRangedWeapon: LocalizedStringKey = "rangedWeapon"
    static let itemsBodyArmor: LocalizedStringKey = "bodyArmor"
    static let itemsHelmet: LocalizedStringKey = "helmet"
    static let itemsShield: LocalizedStringKey = "shield"
    static let itemsTool: LocalizedStringKey = "tool"
    static let itemsGoods: LocalizedStringKey = "goods"
    static let itemsMiscellaneous: LocalizedStringKey = "miscellaneous"
    static let itemsMeleeWeaponPlural: LocalizedStringKey = "meleeWeapons"
    static let itemsRangedWeaponPlural: LocalizedStringKey = "rangedWeapons"
    static let itemsBodyArmorPlural: LocalizedStringKey = "bodyArmors"
    static let itemsHelmetPlural: LocalizedStringKey = "helmets"
    static let itemsShieldPlural: LocalizedStringKey = "shields"
    static let itemsToolPlural: LocalizedStringKey = "tools"
    static let itemsGoodsPlural: LocalizedStringKey = "goodsPlural"
    static let itemsMiscellaneousPlural: LocalizedStringKey = "miscellaneousPlural"
    
    // MARK: - Body armors
    static let bodyArmorLeather: LocalizedStringKey = "bodyArmorLeather"
    static let bodyArmorStuddedLeather: LocalizedStringKey = "bodyArmorStuddedLeather"
    static let bodyArmorChainmail: LocalizedStringKey = "bodyArmorChainmail"
    static let bodyArmorPlate: LocalizedStringKey = "bodyArmorPlate"
    static let bodyArmorChainmailDescription: LocalizedStringKey = "bodyArmorChainmailDescription"
    static let bodyArmorPlateDescription: LocalizedStringKey = "bodyArmorPlateDescription"
    
    // MARK: - Helmets
    static let helmetStuddedLeatherCap: LocalizedStringKey = "studdedLeatherCap"
    static let helmetOpenHelmet: LocalizedStringKey = "openHelmet"
    static let helmetClosedHelmet: LocalizedStringKey = "closedHelmet"
    static let helmetGreatHelm: LocalizedStringKey = "greatHelm"
    static let helmetGreatHelmDescription: LocalizedStringKey = "greatHelmDescription"
    
    // MARK: - Shields
    static let shieldSmall: LocalizedStringKey = "shieldSmall"
    static let shieldLarge: LocalizedStringKey = "shieldLarge"
    
    // MARK: - Melee weapons
    static let meleeWeaponUnarmed: LocalizedStringKey = "unarmed"
    static let meleeWeaponKnife: LocalizedStringKey = "knife"
    static let meleeWeaponDagger: LocalizedStringKey = "dagger"
    static let meleeWeaponFalchion: LocalizedStringKey = "falchion"
    static let meleeWeaponShortsword: LocalizedStringKey = "shortsword"
    static let meleeWeaponBroadsword: LocalizedStringKey = "broadsword"
    static let meleeWeaponLongsword: LocalizedStringKey = "longsword"
    static let meleeWeaponTwoHandedSword: LocalizedStringKey = "twoHandedSword"
    static let meleeWeaponScimitar: LocalizedStringKey = "scimitar"
    static let meleeWeaponHandaxe: LocalizedStringKey = "handaxe"
    static let meleeWeaponBattleaxe: LocalizedStringKey = "battleaxe"
    static let meleeWeaponTwoHandedAxe: LocalizedStringKey = "twoHandedAxe"
    static let meleeWeaponMace: LocalizedStringKey = "mace"
    static let meleeWeaponMorningstar: LocalizedStringKey = "morningstar"
    static let meleeWeaponWarhammer: LocalizedStringKey = "warhammer"
    static let meleeWeaponFlail: LocalizedStringKey = "flail"
    static let meleeWeaponWoodenClub: LocalizedStringKey = "woodenClub"
    static let meleeWeaponLargeWoodenClub: LocalizedStringKey = "largeWoodenClub"
    static let meleeWeaponHeavyWarhammer: LocalizedStringKey = "heavyWarhammer"
    static let meleeWeaponStaff: LocalizedStringKey = "staff"
    static let meleeWeaponShortSpear: LocalizedStringKey = "shortSpear"
    static let meleeWeaponLongSpear: LocalizedStringKey = "longSpear"
    static let meleeWeaponPike: LocalizedStringKey = "pike"
    static let meleeWeaponHalberd: LocalizedStringKey = "halberd"
    static let meleeWeaponTrident: LocalizedStringKey = "trident"
    
    // MARK: - Ranged weapons
    static let rangedWeaponRock: LocalizedStringKey = "rock"
    static let rangedWeaponThrowingKnife: LocalizedStringKey = "throwingKnife"
    static let rangedWeaponThrowingAxe: LocalizedStringKey = "throwingAxe"
    static let rangedWeaponThrowingSpear: LocalizedStringKey = "throwingSpear"
    static let rangedWeaponSling: LocalizedStringKey = "sling"
    static let rangedWeaponShortBow: LocalizedStringKey = "shortBow"
    static let rangedWeaponLongbow: LocalizedStringKey = "longbow"
    static let rangedWeaponLightCrossbow: LocalizedStringKey = "lightCrossbow"
    static let rangedWeaponHeavyCrossbow: LocalizedStringKey = "heavyCrossbow"
    
    // MARK: - Weapon features
    static let weaponFeatureBlunt: LocalizedStringKey = "bluntWeapon"
    static let weaponFeaturePointed: LocalizedStringKey = "pointedWeapon"
    static let weaponFeatureEdged: LocalizedStringKey = "edgedWeapon"
    static let weaponFeatureParrying: LocalizedStringKey = "parryingWeapon"
    static let weaponFeatureLight: LocalizedStringKey = "lightWeapon"
    static let weaponFeatureHeavy: LocalizedStringKey = "heavyWeapon"
    static let weaponFeatureHook: LocalizedStringKey = "hookWeapon"
    static let weaponFeatureLoadingIsSlowAction: LocalizedStringKey = "loadingIsSlowAction"
    
    // MARK: - Weapon grip
    static let weaponGripOneHanded: LocalizedStringKey = "oneHanded"
    static let weaponGripTwoHanded: LocalizedStringKey = "twoHanded"
    
    // MARK: - Tools
    static let toolSaw: LocalizedStringKey = "saw"
    static let toolHammer: LocalizedStringKey = "hammer"
    static let toolSledgeHammer: LocalizedStringKey = "sledgeHammer"
    static let toolPickaxe: LocalizedStringKey = "pickaxe"
    static let toolShovel: LocalizedStringKey = "shovel"
    static let toolTimberAxe: LocalizedStringKey = "timberAxe"
    static let toolPliers: LocalizedStringKey = "pliers"
    static let toolNeedleAndThread: LocalizedStringKey = "needleAndThread"
    
    // MARK: - Items headers
    static let itemHeaderItem: LocalizedStringKey = "itemHeaderItem"
    static let itemHeaderPrice: LocalizedStringKey = "itemHeaderPrice"
    static let itemHeaderSupply: LocalizedStringKey = "itemHeaderSupply"
    static let itemHeaderWeight: LocalizedStringKey = "itemHeaderWeight"
    static let itemHeaderRawMaterials: LocalizedStringKey = "itemHeaderRawMaterials"
    static let itemHeaderTime: LocalizedStringKey = "itemHeaderTime"
    static let itemHeaderTalent: LocalizedStringKey = "itemHeaderTalent"
    static let itemHeaderTools: LocalizedStringKey = "itemHeaderTools"
    static let itemHeaderEffect: LocalizedStringKey = "itemHeaderEffect"
    static let itemHeaderWeapon: LocalizedStringKey = "itemHeaderWeapon"
    
    // MARK: - Kin
    static let kinHumanMale: LocalizedStringKey = "humanMale"
    static let kinElfMale: LocalizedStringKey = "elfMale"
    static let kinHalfElfMale: LocalizedStringKey = "halfElfMale"
    static let kinDwarfMale: LocalizedStringKey = "dwarfMale"
    static let kinOrcMale: LocalizedStringKey = "orcMale"
    static let kinWolfkinMale: LocalizedStringKey = "wolfkinMale"
    static let kinHalflingMale: LocalizedStringKey = "halflingMale"
    static let kinGoblinMale: LocalizedStringKey = "goblinMale"
    static let kinHumanFemale: LocalizedStringKey = "humanFemale"
    static let kinElfFemale: LocalizedStringKey = "elfFemale"
    static let kinHalfElfFemale: LocalizedStringKey = "halfElfFemale"
    static let kinDwarfFemale: LocalizedStringKey = "dwarfFemale"
    static let kinOrcFemale: LocalizedStringKey = "orcFemale"
    static let kinWolfkinFemale: LocalizedStringKey = "wolfkinFemale"
    static let kinHalflingFemale: LocalizedStringKey = "halflingFemale"
    static let kinGoblinFemale: LocalizedStringKey = "goblinFemale"
    
    // MARK: - Profession
    static let professionDruidMale: LocalizedStringKey = "druidMale"
    static let professionFighterMale: LocalizedStringKey = "fighterMale"
    static let professionHunterMale: LocalizedStringKey = "hunterMale"
    static let professionMinstrelMale: LocalizedStringKey = "minstrelMale"
    static let professionPeddlerMale: LocalizedStringKey = "peddlerMale"
    static let professionRiderMale: LocalizedStringKey = "riderMale"
    static let professionRogueMale: LocalizedStringKey = "rogueMale"
    static let professionSorcererMale: LocalizedStringKey = "sorcererMale"
    static let professionOtherMale: LocalizedStringKey = "otherMale"
    static let professionDruidFemale: LocalizedStringKey = "druidFemale"
    static let professionFighterFemale: LocalizedStringKey = "fighterFemale"
    static let professionHunterFemale: LocalizedStringKey = "hunterFemale"
    static let professionMinstrelFemale: LocalizedStringKey = "minstrelFemale"
    static let professionPeddlerFemale: LocalizedStringKey = "peddlerFemale"
    static let professionRiderFemale: LocalizedStringKey = "riderFemale"
    static let professionRogueFemale: LocalizedStringKey = "rogueFemale"
    static let professionSorcererFemale: LocalizedStringKey = "sorcererFemale"
    static let professionOtherFemale: LocalizedStringKey = "otherFemale"
    
}
