//
// © 2023 Manicek
//

import SwiftUI

extension LocalizedStringKey {
    // MARK: - Special
    static let empty: LocalizedStringKey = "-"
    
    // MARK: - MainView titles
    static let mainViewTitlePlayers: LocalizedStringKey = "players"
    static let mainViewTitlePlaces: LocalizedStringKey = "places"
    static let mainViewTitleCombat: LocalizedStringKey = "combat"
    static let mainViewTitleTables: LocalizedStringKey = "tables"
    static let mainViewTitleRolling: LocalizedStringKey = "rolling"
    static let mainViewTitleTalents: LocalizedStringKey = "talents"
    static let mainViewTitleEncounters: LocalizedStringKey = "encounters"
    static let mainViewTitleNPCs: LocalizedStringKey = "npcs"
    
    // MARK: - Money
    static let coinCopper: LocalizedStringKey = "copperCoin"
    static let coinCopperSome: LocalizedStringKey = "copperCoinsSome"
    static let coinCopperMany: LocalizedStringKey = "copperCoinsMany"
    static let coinSilver: LocalizedStringKey = "silverCoin"
    static let coinSilverSome: LocalizedStringKey = "silverCoinsSome"
    static let coinSilverMany: LocalizedStringKey = "silverCoinsMany"
    static let coinGold: LocalizedStringKey = "goldCoin"
    static let coinGoldSome: LocalizedStringKey = "goldCoinsSome"
    static let coinGoldMany: LocalizedStringKey = "goldCoinsMany"
    
    // MARK: - Character
    static let characterPride: LocalizedStringKey = "pride"
    static let characterDarkSecret: LocalizedStringKey = "darkSecret"
    static let characterReputation: LocalizedStringKey = "reputation"
    static let characterAge: LocalizedStringKey = "age"
    static let characterGenderMale: LocalizedStringKey = "genderMale"
    static let characterGenderFemale: LocalizedStringKey = "genderFemale"
    static let characterGenderOther: LocalizedStringKey = "genderOther"
    static let characterLevel: LocalizedStringKey = "level"
    static let characterRank: LocalizedStringKey = "rank"
    static let characterWillpower: LocalizedStringKey = "willpower"
    static let characterExperience: LocalizedStringKey = "experience"
    
    // MARK: - Attributes
    static let attributes: LocalizedStringKey = "attributes"
    static let attributesStrength: LocalizedStringKey = "strength"
    static let attributesAgility: LocalizedStringKey = "agility"
    static let attributesWits: LocalizedStringKey = "wits"
    static let attributesEmpathy: LocalizedStringKey = "empathy"
    
    // MARK: - Skills
    static let skills: LocalizedStringKey = "skills"
    static let skillsMight: LocalizedStringKey = "might"
    static let skillsEndurance: LocalizedStringKey = "endurance"
    static let skillsMelee: LocalizedStringKey = "melee"
    static let skillsCrafting: LocalizedStringKey = "crafting"
    static let skillsStealth: LocalizedStringKey = "stealth"
    static let skillsSleightOfHand: LocalizedStringKey = "sleightOfHand"
    static let skillsMove: LocalizedStringKey = "move"
    static let skillsMarksmanship: LocalizedStringKey = "marksmanship"
    static let skillsScouting: LocalizedStringKey = "scouting"
    static let skillsLore: LocalizedStringKey = "lore"
    static let skillsSurvival: LocalizedStringKey = "survival"
    static let skillsInsight: LocalizedStringKey = "insight"
    static let skillsManipulation: LocalizedStringKey = "manipulation"
    static let skillsPerformance: LocalizedStringKey = "performance"
    static let skillsHealing: LocalizedStringKey = "healing"
    static let skillsAnimalHandling: LocalizedStringKey = "animalHandling"
    
    // MARK: - Talents
    static let talents: LocalizedStringKey = "talents"
    static let talentAdaptive: LocalizedStringKey = "adaptive"
    static let talentInnerPeace: LocalizedStringKey = "innerPeace"
    static let talentPsychicPower: LocalizedStringKey = "psychicPower"
    static let talentTrueGrit: LocalizedStringKey = "trueGrit"
    static let talentHardToCatch: LocalizedStringKey = "hardToCatch"
    static let talentHuntingInstincts: LocalizedStringKey = "huntingInstincts"
    static let talentUnbreakable: LocalizedStringKey = "unbreakable"
    static let talentNocturnal: LocalizedStringKey = "nocturnal"
    static let talentPathOfHealing: LocalizedStringKey = "pathOfHealing"
    static let talentPathOfShiftingShapes: LocalizedStringKey = "pathOfShiftingShapes"
    static let talentPathOfSight: LocalizedStringKey = "pathOfSight"
    static let talentPathOfTheBlade: LocalizedStringKey = "pathOfTheBlade"
    static let talentPathOfTheEnemy: LocalizedStringKey = "pathOfTheEnemy"
    static let talentPathOfTheShield: LocalizedStringKey = "pathOfTheShield"
    static let talentPathOfTheArrow: LocalizedStringKey = "pathOfTheArrow"
    static let talentPathOfTheBeast: LocalizedStringKey = "pathOfTheBeast"
    static let talentPathOfTheForest: LocalizedStringKey = "pathOfTheForest"
    static let talentPathOfTheHymn: LocalizedStringKey = "pathOfTheHymn"
    static let talentPathOfTheSong: LocalizedStringKey = "pathOfTheSong"
    static let talentPathOfTheWarcry: LocalizedStringKey = "pathOfTheWarcry"
    static let talentPathOfTreasures: LocalizedStringKey = "pathOfTreasures"
    static let talentPathOfWords: LocalizedStringKey = "pathOfWords"
    static let talentPathOfManyThings: LocalizedStringKey = "pathOfManyThings"
    static let talentPathOfTheCompanion: LocalizedStringKey = "pathOfTheCompanion"
    static let talentPathOfTheKnight: LocalizedStringKey = "pathOfTheKnight"
    static let talentPathOfThePlains: LocalizedStringKey = "pathOfThePlains"
    static let talentPathOfTheFace: LocalizedStringKey = "pathOfTheFace"
    static let talentPathOfTheKiller: LocalizedStringKey = "pathOfTheKiller"
    static let talentPathOfPoison: LocalizedStringKey = "pathOfPoison"
    static let talentPathOfBlood: LocalizedStringKey = "pathOfBlood"
    static let talentPathOfDeath: LocalizedStringKey = "pathOfDeath"
    static let talentPathOfSigns: LocalizedStringKey = "pathOfSigns"
    static let talentPathOfStone: LocalizedStringKey = "pathOfStone"
    static let talentAmbidextrous: LocalizedStringKey = "ambidextrous"
    static let talentAxeFighter: LocalizedStringKey = "axeFighter"
    static let talentBerserker: LocalizedStringKey = "berserker"
    static let talentBowyer: LocalizedStringKey = "bowyer"
    static let talentBrawler: LocalizedStringKey = "brawler"
    static let talentBuilder: LocalizedStringKey = "builder"
    static let talentChef: LocalizedStringKey = "chef"
    static let talentColdBlooded: LocalizedStringKey = "coldBlooded"
    static let talentDefender: LocalizedStringKey = "defender"
    static let talentDragonslayer: LocalizedStringKey = "dragonslayer"
    static let talentExecutioner: LocalizedStringKey = "executioner"
    static let talentFastFootwork: LocalizedStringKey = "fastFootwork"
    static let talentFastShooter: LocalizedStringKey = "fastShooter"
    static let talentFearless: LocalizedStringKey = "fearless"
    static let talentFirmGrip: LocalizedStringKey = "firmGrip"
    static let talentFisher: LocalizedStringKey = "fisher"
    static let talentHammerFighter: LocalizedStringKey = "hammerFighter"
    static let talentHerbalist: LocalizedStringKey = "herbalist"
    static let talentHorsebackFighter: LocalizedStringKey = "horsebackFighter"
    static let talentIncorruptible: LocalizedStringKey = "incorruptible"
    static let talentKnifeFighter: LocalizedStringKey = "knifeFighter"
    static let talentLightningFast: LocalizedStringKey = "lightningFast"
    static let talentLockpicker: LocalizedStringKey = "lockpicker"
    static let talentLucky: LocalizedStringKey = "lucky"
    static let talentMasterOfTheHunt: LocalizedStringKey = "masterOfTheHunt"
    static let talentMeleeCharge: LocalizedStringKey = "meleeCharge"
    static let talentPackRat: LocalizedStringKey = "packRat"
    static let talentPainResistant: LocalizedStringKey = "painResistant"
    static let talentPathfinder: LocalizedStringKey = "pathfinder"
    static let talentPoisoner: LocalizedStringKey = "poisoner"
    static let talentQuartermaster: LocalizedStringKey = "quartermaster"
    static let talentQuickdraw: LocalizedStringKey = "quickdraw"
    static let talentSailor: LocalizedStringKey = "sailor"
    static let talentSharpshooter: LocalizedStringKey = "sharpshooter"
    static let talentSharpTongue: LocalizedStringKey = "sharpTongue"
    static let talentShieldFighter: LocalizedStringKey = "shieldFighter"
    static let talentSixthSense: LocalizedStringKey = "sixthSense"
    static let talentSmith: LocalizedStringKey = "smith"
    static let talentSpearFighter: LocalizedStringKey = "spearFighter"
    static let talentSteadyFeet: LocalizedStringKey = "steadyFeet"
    static let talentSwordFighter: LocalizedStringKey = "swordFighter"
    static let talentTailor: LocalizedStringKey = "tailor"
    static let talentTanner: LocalizedStringKey = "tanner"
    static let talentThreatening: LocalizedStringKey = "threatening"
    static let talentThrowingArm: LocalizedStringKey = "throwingArm"
    static let talentWanderer: LocalizedStringKey = "wanderer"
    
    // MARK: - Conditions
    static let conditions: LocalizedStringKey = "conditions"
    static let conditionsSleepy: LocalizedStringKey = "sleepy"
    static let conditionsThirsty: LocalizedStringKey = "thirsty"
    static let conditionsHungry: LocalizedStringKey = "hungry"
    static let conditionsCold: LocalizedStringKey = "cold"
    
    // MARK: - Consumables
    static let consumables: LocalizedStringKey = "consumables"
    static let consumableFood: LocalizedStringKey = "food"
    static let consumableWater: LocalizedStringKey = "water"
    static let consumableArrows: LocalizedStringKey = "arrows"
    static let consumableTorches: LocalizedStringKey = "torches"
    
    // MARK: - Items
    static let itemsMeleeWeapon: LocalizedStringKey = "meleeWeapon"
    static let itemsRangedWeapon: LocalizedStringKey = "rangedWeapon"
    static let itemsBodyArmor: LocalizedStringKey = "bodyArmor"
    static let itemsHelmet: LocalizedStringKey = "helmet"
    static let itemsShield: LocalizedStringKey = "shield"
    static let itemsTool: LocalizedStringKey = "tool"
    static let itemsGoods: LocalizedStringKey = "goods"
    static let itemsMiscellaneous: LocalizedStringKey = "miscellaneous"
    static let itemsMeleeWeaponPlural: LocalizedStringKey = "meleeWeapons"
    static let itemsRangedWeaponPlural: LocalizedStringKey = "rangedWeapons"
    static let itemsBodyArmorPlural: LocalizedStringKey = "bodyArmors"
    static let itemsHelmetPlural: LocalizedStringKey = "helmets"
    static let itemsShieldPlural: LocalizedStringKey = "shields"
    static let itemsToolPlural: LocalizedStringKey = "tools"
    static let itemsGoodsPlural: LocalizedStringKey = "goodsPlural"
    static let itemsMiscellaneousPlural: LocalizedStringKey = "miscellaneousPlural"
    
    // MARK: - Body armors
    static let bodyArmorLeather: LocalizedStringKey = "bodyArmorLeather"
    static let bodyArmorStuddedLeather: LocalizedStringKey = "bodyArmorStuddedLeather"
    static let bodyArmorChainmail: LocalizedStringKey = "bodyArmorChainmail"
    static let bodyArmorPlate: LocalizedStringKey = "bodyArmorPlate"
    static let bodyArmorChainmailDescription: LocalizedStringKey = "bodyArmorChainmailDescription"
    static let bodyArmorPlateDescription: LocalizedStringKey = "bodyArmorPlateDescription"
    
    // MARK: - Helmets
    static let helmetStuddedLeatherCap: LocalizedStringKey = "studdedLeatherCap"
    static let helmetOpenHelmet: LocalizedStringKey = "openHelmet"
    static let helmetClosedHelmet: LocalizedStringKey = "closedHelmet"
    static let helmetGreatHelm: LocalizedStringKey = "greatHelm"
    static let helmetGreatHelmDescription: LocalizedStringKey = "greatHelmDescription"
    
    // MARK: - Shields
    static let shieldSmall: LocalizedStringKey = "shieldSmall"
    static let shieldLarge: LocalizedStringKey = "shieldLarge"
    
    // MARK: - Melee weapons
    static let meleeWeaponUnarmed: LocalizedStringKey = "unarmed"
    static let meleeWeaponKnife: LocalizedStringKey = "knife"
    static let meleeWeaponDagger: LocalizedStringKey = "dagger"
    static let meleeWeaponFalchion: LocalizedStringKey = "falchion"
    static let meleeWeaponShortsword: LocalizedStringKey = "shortsword"
    static let meleeWeaponBroadsword: LocalizedStringKey = "broadsword"
    static let meleeWeaponLongsword: LocalizedStringKey = "longsword"
    static let meleeWeaponTwoHandedSword: LocalizedStringKey = "twoHandedSword"
    static let meleeWeaponScimitar: LocalizedStringKey = "scimitar"
    static let meleeWeaponHandaxe: LocalizedStringKey = "handaxe"
    static let meleeWeaponBattleaxe: LocalizedStringKey = "battleaxe"
    static let meleeWeaponTwoHandedAxe: LocalizedStringKey = "twoHandedAxe"
    static let meleeWeaponMace: LocalizedStringKey = "mace"
    static let meleeWeaponMorningstar: LocalizedStringKey = "morningstar"
    static let meleeWeaponWarhammer: LocalizedStringKey = "warhammer"
    static let meleeWeaponFlail: LocalizedStringKey = "flail"
    static let meleeWeaponWoodenClub: LocalizedStringKey = "woodenClub"
    static let meleeWeaponLargeWoodenClub: LocalizedStringKey = "largeWoodenClub"
    static let meleeWeaponHeavyWarhammer: LocalizedStringKey = "heavyWarhammer"
    static let meleeWeaponStaff: LocalizedStringKey = "staff"
    static let meleeWeaponShortSpear: LocalizedStringKey = "shortSpear"
    static let meleeWeaponLongSpear: LocalizedStringKey = "longSpear"
    static let meleeWeaponPike: LocalizedStringKey = "pike"
    static let meleeWeaponHalberd: LocalizedStringKey = "halberd"
    static let meleeWeaponTrident: LocalizedStringKey = "trident"
    
    // MARK: - Ranged weapons
    static let rangedWeaponRock: LocalizedStringKey = "rock"
    static let rangedWeaponThrowingKnife: LocalizedStringKey = "throwingKnife"
    static let rangedWeaponThrowingAxe: LocalizedStringKey = "throwingAxe"
    static let rangedWeaponThrowingSpear: LocalizedStringKey = "throwingSpear"
    static let rangedWeaponSling: LocalizedStringKey = "sling"
    static let rangedWeaponShortBow: LocalizedStringKey = "shortBow"
    static let rangedWeaponLongbow: LocalizedStringKey = "longbow"
    static let rangedWeaponLightCrossbow: LocalizedStringKey = "lightCrossbow"
    static let rangedWeaponHeavyCrossbow: LocalizedStringKey = "heavyCrossbow"
    
    // MARK: - Weapon features
    static let weaponFeatureBlunt: LocalizedStringKey = "bluntWeapon"
    static let weaponFeaturePointed: LocalizedStringKey = "pointedWeapon"
    static let weaponFeatureEdged: LocalizedStringKey = "edgedWeapon"
    static let weaponFeatureParrying: LocalizedStringKey = "parryingWeapon"
    static let weaponFeatureLight: LocalizedStringKey = "lightWeapon"
    static let weaponFeatureHeavy: LocalizedStringKey = "heavyWeapon"
    static let weaponFeatureHook: LocalizedStringKey = "hookWeapon"
    static let weaponFeatureLoadingIsSlowAction: LocalizedStringKey = "loadingIsSlowAction"
    
    // MARK: - Weapon grip
    static let weaponGripOneHanded: LocalizedStringKey = "oneHanded"
    static let weaponGripTwoHanded: LocalizedStringKey = "twoHanded"
    
    // MARK: - Tools
    static let toolSaw: LocalizedStringKey = "saw"
    static let toolHammer: LocalizedStringKey = "hammer"
    static let toolSledgeHammer: LocalizedStringKey = "sledgeHammer"
    static let toolPickaxe: LocalizedStringKey = "pickaxe"
    static let toolShovel: LocalizedStringKey = "shovel"
    static let toolTimberAxe: LocalizedStringKey = "timberAxe"
    static let toolPliers: LocalizedStringKey = "pliers"
    static let toolNeedleAndThread: LocalizedStringKey = "needleAndThread"
    
    // MARK: - Items headers
    static let itemHeaderItem: LocalizedStringKey = "itemHeaderItem"
    static let itemHeaderPrice: LocalizedStringKey = "itemHeaderPrice"
    static let itemHeaderSupply: LocalizedStringKey = "itemHeaderSupply"
    static let itemHeaderWeight: LocalizedStringKey = "itemHeaderWeight"
    static let itemHeaderRawMaterials: LocalizedStringKey = "itemHeaderRawMaterials"
    static let itemHeaderTime: LocalizedStringKey = "itemHeaderTime"
    static let itemHeaderTalent: LocalizedStringKey = "itemHeaderTalent"
    static let itemHeaderTools: LocalizedStringKey = "itemHeaderTools"
    static let itemHeaderEffect: LocalizedStringKey = "itemHeaderEffect"
    static let itemHeaderWeapon: LocalizedStringKey = "itemHeaderWeapon"
    
    // MARK: - Weapon headers
    static let weaponHeaderWeapons: LocalizedStringKey = "weapons"
    static let weaponHeaderBonus: LocalizedStringKey = "bonus"
    static let weaponHeaderDamage: LocalizedStringKey = "damage"
    static let weaponHeaderRange: LocalizedStringKey = "range"
    static let weaponHeaderComment: LocalizedStringKey = "comment"
    
    // MARK: - Kin
    static let kinHumanMale: LocalizedStringKey = "humanMale"
    static let kinElfMale: LocalizedStringKey = "elfMale"
    static let kinHalfElfMale: LocalizedStringKey = "halfElfMale"
    static let kinDwarfMale: LocalizedStringKey = "dwarfMale"
    static let kinOrcMale: LocalizedStringKey = "orcMale"
    static let kinWolfkinMale: LocalizedStringKey = "wolfkinMale"
    static let kinHalflingMale: LocalizedStringKey = "halflingMale"
    static let kinGoblinMale: LocalizedStringKey = "goblinMale"
    static let kinHumanFemale: LocalizedStringKey = "humanFemale"
    static let kinElfFemale: LocalizedStringKey = "elfFemale"
    static let kinHalfElfFemale: LocalizedStringKey = "halfElfFemale"
    static let kinDwarfFemale: LocalizedStringKey = "dwarfFemale"
    static let kinOrcFemale: LocalizedStringKey = "orcFemale"
    static let kinWolfkinFemale: LocalizedStringKey = "wolfkinFemale"
    static let kinHalflingFemale: LocalizedStringKey = "halflingFemale"
    static let kinGoblinFemale: LocalizedStringKey = "goblinFemale"
    
    // MARK: - Profession
    static let professionDruidMale: LocalizedStringKey = "druidMale"
    static let professionFighterMale: LocalizedStringKey = "fighterMale"
    static let professionHunterMale: LocalizedStringKey = "hunterMale"
    static let professionMinstrelMale: LocalizedStringKey = "minstrelMale"
    static let professionPeddlerMale: LocalizedStringKey = "peddlerMale"
    static let professionRiderMale: LocalizedStringKey = "riderMale"
    static let professionRogueMale: LocalizedStringKey = "rogueMale"
    static let professionSorcererMale: LocalizedStringKey = "sorcererMale"
    static let professionOtherMale: LocalizedStringKey = "otherMale"
    static let professionDruidFemale: LocalizedStringKey = "druidFemale"
    static let professionFighterFemale: LocalizedStringKey = "fighterFemale"
    static let professionHunterFemale: LocalizedStringKey = "hunterFemale"
    static let professionMinstrelFemale: LocalizedStringKey = "minstrelFemale"
    static let professionPeddlerFemale: LocalizedStringKey = "peddlerFemale"
    static let professionRiderFemale: LocalizedStringKey = "riderFemale"
    static let professionRogueFemale: LocalizedStringKey = "rogueFemale"
    static let professionSorcererFemale: LocalizedStringKey = "sorcererFemale"
    static let professionOtherFemale: LocalizedStringKey = "otherFemale"
    
    // MARK: - Range
    static let rangeArm: LocalizedStringKey = "rangeArm"
    static let rangeNear: LocalizedStringKey = "rangeNear"
    static let rangeShort: LocalizedStringKey = "rangeShort"
    static let rangeLong: LocalizedStringKey = "rangeLong"
    static let rangeDistant: LocalizedStringKey = "rangeDistant"
    
    // MARK: - Animals
    static let animalBear: LocalizedStringKey = "bear"
    static let animalWolf: LocalizedStringKey = "wolf"
    static let animalFox: LocalizedStringKey = "fox"
    static let animalDeer: LocalizedStringKey = "deer"
    static let animalBoar: LocalizedStringKey = "boar"
    static let animalHorse: LocalizedStringKey = "horse"
    static let animalWarhorse: LocalizedStringKey = "warhorse"
    static let animalDonkey: LocalizedStringKey = "donkey"
    static let animalWardog: LocalizedStringKey = "wardog"
    static let animalCrocodile: LocalizedStringKey = "crocodile"
    static let animalDog: LocalizedStringKey = "dog"
    static let animalCat: LocalizedStringKey = "cat"
    static let animalRats: LocalizedStringKey = "rats"
    static let animalBats: LocalizedStringKey = "bats"
    static let animalRaven: LocalizedStringKey = "raven"
    static let animalEagle: LocalizedStringKey = "eagle"
    static let animalSnake: LocalizedStringKey = "snake"
    static let animalScorpion: LocalizedStringKey = "scorpion"
    static let animalSpider: LocalizedStringKey = "spider"
    
    // MARK: - Dice
    static let d6: LocalizedStringKey = "d6"
    static let d8: LocalizedStringKey = "d8"
    static let d10: LocalizedStringKey = "d10"
    static let d12: LocalizedStringKey = "d12"
    
    // MARK: - Supply
    static let supplyCommon: LocalizedStringKey = "supplyCommon"
    static let supplyUncommon: LocalizedStringKey = "supplyUncommon"
    static let supplyRare: LocalizedStringKey = "supplyRare"
    
    // MARK: - Weight
    static let weightTiny: LocalizedStringKey = "weightTiny"
    static let weightLight: LocalizedStringKey = "weightLight"
    static let weightNormal: LocalizedStringKey = "weightNormal"
    static let weightHeavy: LocalizedStringKey = "weightHeavy"
    
    // MARK: - Crafting times
    static let craftingTimeQuarterDay: LocalizedStringKey = "craftingTimeQuarterDay"
    static let craftingTimeOneDay: LocalizedStringKey = "craftingTimeOneDay"
    static let craftingTimeTwoDays: LocalizedStringKey = "craftingTimeTwoDays"
    static let craftingTimeOneWeek: LocalizedStringKey = "craftingTimeOneWeek"
    static let craftingTimeTwoWeeks: LocalizedStringKey = "craftingTimeTwoWeeks"
    
    // MARK: - Special requirements
    static let specialRequirementFire: LocalizedStringKey = "fire"
    static let specialRequirementForge: LocalizedStringKey = "forge"
    static let specialRequirementStone: LocalizedStringKey = "stone"
    static let specialRequirementKnife: LocalizedStringKey = "knife"
    static let specialRequirementInkAndQuill: LocalizedStringKey = "inkAndQuill"
    static let specialRequirementCauldron: LocalizedStringKey = "cauldron"
    
    // MARK: - Raw materials
    static let materialIron: LocalizedStringKey = "materialIron"
    static let materialIronSome: LocalizedStringKey = "materialIronSome"
    static let materialIronMany: LocalizedStringKey = "materialIronMany"
    static let materialLeather: LocalizedStringKey = "materialLeather"
    static let materialLeatherSome: LocalizedStringKey = "materialLeatherSome"
    static let materialLeatherMany: LocalizedStringKey = "materialLeatherMany"
    static let materialWood: LocalizedStringKey = "materialWood"
    static let materialWoodSome: LocalizedStringKey = "materialWoodSome"
    static let materialWoodMany: LocalizedStringKey = "materialWoodMany"
    static let materialCloth: LocalizedStringKey = "materialCloth"
    static let materialClothSome: LocalizedStringKey = "materialClothSome"
    static let materialClothMany: LocalizedStringKey = "materialClothMany"
    static let materialPelt: LocalizedStringKey = "materialPelt"
    static let materialPeltSome: LocalizedStringKey = "materialPeltSome"
    static let materialPeltMany: LocalizedStringKey = "materialPeltMany"
    static let materialGlass: LocalizedStringKey = "materialGlass"
    static let materialGlassSome: LocalizedStringKey = "materialGlassSome"
    static let materialGlassMany: LocalizedStringKey = "materialGlassMany"
    static let materialTallow: LocalizedStringKey = "materialTallow"
    static let materialTallowSome: LocalizedStringKey = "materialTallowSome"
    static let materialTallowMany: LocalizedStringKey = "materialTallowMany"
    static let materialStone: LocalizedStringKey = "materialStone"
    static let materialStoneSome: LocalizedStringKey = "materialStoneSome"
    static let materialStoneMany: LocalizedStringKey = "materialStoneMany"
    static let materialStonePieceOf: LocalizedStringKey = "materialStonePieceOf"
    static let materialSilver: LocalizedStringKey = "materialSilver"
    static let materialSilverSome: LocalizedStringKey = "materialSilverSome"
    static let materialSilverMany: LocalizedStringKey = "materialSilverMany"
    static let materialMeatFishOrVegetables: LocalizedStringKey = "materialMeatFishOrVegetables"
    static let materialFeather: LocalizedStringKey = "feather"
    static let materialHerbs: LocalizedStringKey = "herbs"
    static let materialIronOre: LocalizedStringKey = "ironOre"
    static let materialWool: LocalizedStringKey = "wool"
    static let materialGrain: LocalizedStringKey = "grain"
    static let materialFlour: LocalizedStringKey = "flour"
    static let materialParchment: LocalizedStringKey = "parchment"
    
    // MARK: - Goods
    static let goodsArrowsIronHead: LocalizedStringKey = "arrowsIronHead"
    static let goodsArrowsWoodenHead: LocalizedStringKey = "arrowsWoodenHead"
    static let goodsQuiver: LocalizedStringKey = "quiver"
    static let goodsGrapplingHook: LocalizedStringKey = "grapplingHook"
    static let goodsRope10Meters: LocalizedStringKey = "rope10Meters"
    static let goodsTallowCandle: LocalizedStringKey = "tallowCandle"
    static let goodsOilLamp: LocalizedStringKey = "oilLamp"
    static let goodsLantern: LocalizedStringKey = "lantern"
    static let goodsTorches: LocalizedStringKey = "torches"
    static let goodsSack: LocalizedStringKey = "sack"
    static let goodsBackpack: LocalizedStringKey = "backpack"
    static let goodsWaterskin: LocalizedStringKey = "waterskin"
    static let goodsBandages: LocalizedStringKey = "bandages"
    static let goodsLampOil: LocalizedStringKey = "lampOil"
    static let goodsInkAndQuill: LocalizedStringKey = "inkAndQuill"
    static let goodsParchment: LocalizedStringKey = "parchment"
    static let goodsBlanket: LocalizedStringKey = "blanket"
    static let goodsSleepingFur: LocalizedStringKey = "sleepingFur"
    static let goodsFlintAndSteel: LocalizedStringKey = "flintAndSteel"
    static let goodsLockpicks: LocalizedStringKey = "lockpicks"
    static let goodsFieldRations: LocalizedStringKey = "fieldRations"
    static let goodsFieldKitchen: LocalizedStringKey = "fieldKitchen"
    static let goodsCauldron: LocalizedStringKey = "cauldron"
    static let goodsMetalChalice: LocalizedStringKey = "metalChalice"
    static let goodsTankard: LocalizedStringKey = "tankard"
    static let goodsMetalPlate: LocalizedStringKey = "metalPlate"
    static let goodsFoodKnife: LocalizedStringKey = "foodKnife"
    static let goodsSpoon: LocalizedStringKey = "spoon"
    static let goodsBearTrap: LocalizedStringKey = "bearTrap"
    static let goodsSnaresCloth: LocalizedStringKey = "snaresCloth"
    static let goodsSnaresLeather: LocalizedStringKey = "snaresLeather"
    static let goodsBarrel: LocalizedStringKey = "barrel"
    static let goodsClayJug: LocalizedStringKey = "clayJug"
    static let goodsSmallTentCloth: LocalizedStringKey = "smallTentCloth"
    static let goodsSmallTentLeather: LocalizedStringKey = "smallTentLeather"
    static let goodsLargeTentCloth: LocalizedStringKey = "largeTentCloth"
    static let goodsLargeTentLeather: LocalizedStringKey = "largeTentLeather"
    static let goodsFishingHookAndLine: LocalizedStringKey = "fishingHookAndLine"
    static let goodsFishingNet: LocalizedStringKey = "fishingNet"
    static let goodsMagnifyingGlass: LocalizedStringKey = "magnifyingGlass"
    static let goodsHolySymbol: LocalizedStringKey = "holySymbol"
    static let goodsChalk: LocalizedStringKey = "chalk"
    static let goodsMap: LocalizedStringKey = "map"
    static let goodsSpyglass: LocalizedStringKey = "spyglass"
    static let goodsCrystalBall: LocalizedStringKey = "crystalBall"
    static let goodsHourglass: LocalizedStringKey = "hourglass"
    static let goodsScales: LocalizedStringKey = "scales"
    static let goodsFlute: LocalizedStringKey = "flute"
    static let goodsHorn: LocalizedStringKey = "horn"
    static let goodsLyre: LocalizedStringKey = "lyre"
    static let goodsHarp: LocalizedStringKey = "harp"
    static let goodsDrum: LocalizedStringKey = "drum"
    static let goodsLethalPoisonOrAntidote: LocalizedStringKey = "lethalPoisonOrAntidote"
    static let goodsParalyzingPoisonOrAntidote: LocalizedStringKey = "paralyzingPoisonOrAntidote"
    static let goodsSleepingPoisonOrAntidote: LocalizedStringKey = "sleepingPoisonOrAntidote"
    static let goodsHallucinogenicPoisonOrAntidote: LocalizedStringKey = "hallucinogenicPoisonOrAntidote"
    
    // MARK: - Item effect
    static let itemEffectArrowsIronHead: LocalizedStringKey = "itemEffectArrowsIronHead"
    static let itemEffectArrowsWoodenHead: LocalizedStringKey = "itemEffectArrowsWoodenHead"
    static let itemEffectQuiver: LocalizedStringKey = "itemEffectQuiver"
    static let itemEffectGrapplingHook: LocalizedStringKey = "itemEffectGrapplingHook"
    static let itemEffectRope10Meters: LocalizedStringKey = "itemEffectRope10Meters"
    static let itemEffectTallowCandle: LocalizedStringKey = "itemEffectTallowCandle"
    static let itemEffectOilLamp: LocalizedStringKey = "itemEffectOilLamp"
    static let itemEffectLantern: LocalizedStringKey = "itemEffectLantern"
    static let itemEffectTorches: LocalizedStringKey = "itemEffectTorches"
    static let itemEffectSack: LocalizedStringKey = "itemEffectSack"
    static let itemEffectBackpack: LocalizedStringKey = "itemEffectBackpack"
    static let itemEffectWaterskin: LocalizedStringKey = "itemEffectWaterskin"
    static let itemEffectBandages: LocalizedStringKey = "itemEffectBandages"
    static let itemEffectLampOil: LocalizedStringKey = "itemEffectLampOil"
    static let itemEffectInkAndQuill: LocalizedStringKey = "itemEffectInkAndQuill"
    static let itemEffectParchment: LocalizedStringKey = "itemEffectParchment"
    static let itemEffectBlanket: LocalizedStringKey = "itemEffectBlanket"
    static let itemEffectSleepingFur: LocalizedStringKey = "itemEffectSleepingFur"
    static let itemEffectFlintAndSteel: LocalizedStringKey = "itemEffectFlintAndSteel"
    static let itemEffectLockpicks: LocalizedStringKey = "itemEffectLockpicks"
    static let itemEffectFieldRations: LocalizedStringKey = "itemEffectFieldRations"
    static let itemEffectFieldKitchen: LocalizedStringKey = "itemEffectFieldKitchen"
    static let itemEffectCauldron: LocalizedStringKey = "itemEffectCauldron"
    static let itemEffectBearTrap: LocalizedStringKey = "itemEffectBearTrap"
    static let itemEffectSnaresCloth: LocalizedStringKey = "itemEffectSnares"
    static let itemEffectSnaresLeather: LocalizedStringKey = "itemEffectSnares"
    static let itemEffectBarrel: LocalizedStringKey = "itemEffectBarrel"
    static let itemEffectClayJug: LocalizedStringKey = "itemEffectClayJug"
    static let itemEffectSmallTentCloth: LocalizedStringKey = "itemEffectSmallTent"
    static let itemEffectSmallTentLeather: LocalizedStringKey = "itemEffectSmallTent"
    static let itemEffectLargeTentCloth: LocalizedStringKey = "itemEffectLargeTent"
    static let itemEffectLargeTentLeather: LocalizedStringKey = "itemEffectLargeTent"
    static let itemEffectFishingHookAndLine: LocalizedStringKey = "itemEffectFishingHookAndLine"
    static let itemEffectFishingNet: LocalizedStringKey = "itemEffectFishingNet"
    static let itemEffectMagnifyingGlass: LocalizedStringKey = "itemEffectMagicIngredient"
    static let itemEffectHolySymbol: LocalizedStringKey = "itemEffectMagicIngredient"
    static let itemEffectChalk: LocalizedStringKey = "itemEffectChalk"
    static let itemEffectMap: LocalizedStringKey = "itemEffectMagicIngredient"
    static let itemEffectSpyglass: LocalizedStringKey = "itemEffectSpyglass"
    static let itemEffectCrystalBall: LocalizedStringKey = "itemEffectMagicIngredient"
    static let itemEffectHourglass: LocalizedStringKey = "itemEffectMagicIngredient"
    static let itemEffectScales: LocalizedStringKey = "itemEffectMagicIngredient"
    static let itemEffectFlute: LocalizedStringKey = "itemEffectInstrument1"
    static let itemEffectHorn: LocalizedStringKey = "itemEffectInstrument1"
    static let itemEffectLyre: LocalizedStringKey = "itemEffectInstrument1"
    static let itemEffectHarp: LocalizedStringKey = "itemEffectInstrument2"
    static let itemEffectDrum: LocalizedStringKey = "itemEffectInstrument1"
    static let itemEffectLethalPoisonOrAntidote: LocalizedStringKey = "itemEffectPoisonOrAntidote"
    static let itemEffectParalyzingPoisonOrAntidote: LocalizedStringKey = "itemEffectPoisonOrAntidote"
    static let itemEffectSleepingPoisonOrAntidote: LocalizedStringKey = "itemEffectPoisonOrAntidote"
    static let itemEffectHallucinogenicPoisonOrAntidote: LocalizedStringKey = "itemEffectPoisonOrAntidote"
    
    // MARK: - Common
    static let commonDay: LocalizedStringKey = "day"
    static let commonDaysSome: LocalizedStringKey = "daysSome"
    static let commonDaysMany: LocalizedStringKey = "daysMany"
    
    // MARK: - Critical injuries
    static let criticalInjuries: LocalizedStringKey = "criticalInjuries"
    static let criticalInjuriesPermanent: LocalizedStringKey = "criticalInjuriesPermanent"
    
    // MARK: - Critical injuries other
    static let criticalInjuriesNonTypicalDamage: LocalizedStringKey = "criticalInjuriesNonTypicalDamage"
    static let criticalInjuriesPushedDamage: LocalizedStringKey = "criticalInjuriesPushedDamage"
    static let criticalInjuriesNonTypicalDamageEffect: LocalizedStringKey = "criticalInjuriesNonTypicalDamageEffect"
    static let criticalInjuriesPushedDamageEffect: LocalizedStringKey = "criticalInjuriesPushedDamageEffect"
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
}
